openstack overcloud update converge --templates \
-r ~/templates/roles_data.yaml.old \
-n ~/templates/network_data.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/network-environment.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml \
-e ~/templates/network.yaml \
-e ~/templates/kvm.yaml \
-e ~/templates/tuning.yaml \
-e ~/templates/root-password.yaml \
-e ~/templates/containers-prepare-parameter.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/docker-ha.yaml \
-e ~/templates/overcloud-passwords.yaml
--ntp pool.ntp.org 
